### ISSUE TITLE
Wow, beautiful - ありがとうございました！

### ISSUE THREAD

**Issue by mspanish** [ics-creative/ParticleJS#1]
I don't really know much Japanese but this is wonderful!!

1 question: can I limit the number of loops?  I am building a reading app for kids with autism (for my daughter who is 4) - and I plan to mainly use particles as fun effects when the child clicks something, or answers something correctly. I will be using them mostly in short bursts of just a few seconds.

I have looked through your api and am not sure if one of your settings will allow me to do that.

thank you again - particlejs = 素晴らしい   !!

**Comment by ics-nohara** [comment]
@mspanish 

I apologize for the late reply.

Sorry. You can not set the number of loops in particlejs.
You can reduce particle generation by putting 0 in the emitFrequency after a while after clicking.

- Sample Code
```
    createjs.Ticker.addEventListener("tick", handleTick);
        
    document.body.addEventListener("click", function () {
       particleSystem.emitFrequency = 30;
       // Generate only 50 frames
        counter = 50;
    });
    function handleTick() {
        particleSystem.update();
        stage.update();
        
        // Count down 
        counter --;
        if( counter <= 0 ) {
            // Stop generation
            particleSystem.emitFrequency = 0;
            counter = 0;
        }
```
http://jsdo.it/nyamogera/KDGi

 I hope this will help.

**Comment by mspanish** [comment]
thanks for the reply! I'm using pixi particles now - but I will keep checking back on this as your project is very lovely, especially the editor!
