### ISSUE TITLE
シェイプのbrur_circleにつきまして

### ISSUE THREAD

**Issue by nakajox** [ics-creative/ParticleJS#3]
ParticleJS、ありがとうございます！
つきましては、シェイプの形状を調整したく、
例えば、
BLUR_CIRCLEのblurを調整したい（blurをもう少しはっきりさせたい）場合、
どのような方法で実現できますでしょうか
お手数をおかけしますがご教示ください

**Comment by ics-nohara** [comment]
@nakajox さん
ご返答が遅くなって申し訳ありません。
シェイプの形状調整する件ですが、新しくCreateJSでシェイプの表示クラスを作る必要があります。particle.jsのjsの読み込みを待った後、次のようにクラスをつくり、`shape`インスタンスを作成し、`graphics`オブジェクトに命令を行い、図形の描画を行います。

CreateJSでの図形の描画例 : [CreateJS での様々な図形の描画方法](https://ics.media/tutorial-createjs/shape_draw.html)

```
// 新しいシェイプクラスの作成
(myCircle = function () {
  this.initialize();

  this.shape = new createjs.Shape();
  this.shape.graphics.beginFill("#FFFFFF").beginStroke().drawEllipse(-10.8, -10.8, 21.7, 21.7);
  this.shape.setTransform(0, 0, 3, 3);

  this.addChild(this.shape);
}).prototype = p = new createjs.Container();
p.nominalBounds = new createjs.Rectangle(-36, -36, 72, 72);

// particleJSから読み込めるクラスとして指定
window.particlejs.assets.myCircle = myCircle;
```

新しく作成したシェイプを適用する方法は、`window.particle.js.assets.作成したクラス名`の`作成したクラス名`をParticleSystemの初期時の`shaderList`に指定します。

```
particleSystem.importFromJson(
  {
    "bgColor": "#00000",
    "width": 838,
    ...略...
    "shapeIdList" : [ "myCircle", ],
....略...
 }
);
```

[サンプルコード](http://jsdo.it/nyamogera/e6aW)

**Comment by nakajox** [comment]
@ics-noharaさま
ご連絡ありがとうございます！
参考にして作成いたします！
素晴らしいライブラリありがとうございます！

**Comment by ics-nohara** [comment]
@nakajox さん
こちらこそ使ってくださってありがとうございます。
参考になれば幸いです。また何かあればお知らせ下さい！
